### ISSUE TITLE
Need help to understand the config-file example

### ISSUE THREAD

**Issue by lightning02** [blueyu2/Strata#1]
How do you figured out what you have to write next to the first line?

In the TConstruct example-config-file the line is:

"TConstruct:SearedBrick:3"
when the folder where the textures are in is asset\tinker\textures\blocks

This make no sense.. what's the point of SearedBrick:3 for example? how do you figure it out?
![cb3d18b620de0a3b091fe0a387bfc7c1045ba0e304beca433a pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15360144/b6ae94ea-1d0c-11e6-878c-cb7e36a49241.png)

In forestry for example is:

   "Forestry:resources" {

but the folder where the textures lies is called "ores" 
Where does comes out "resources"?
![e2f93f0cb78e3adf2de988c4e0eaeb6de37614a8eb7bdc01e9 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15360159/cb515720-1d0c-11e6-9427-7d5484e21069.png)

And how I can understand what for example is needed next to "industustrialcraft-2"?
![aecef2bd96c9dcc477c179e773a2ff41c709e9bfddff3ef10b pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15360272/3ba84c68-1d0d-11e6-85a6-712b089608ac.png)

**Comment by blueyu2** [comment]
TConstruct:SearedBrick:3 is not a reference to the block texture, but instead refers to the block ID and metadata for the copper ore block added by Tinkers Construct. I found that out by installing the mod [MineTweaker3](http://minecraft.curseforge.com/projects/minetweaker3), and in a creative world giving myself the copper ore block, and while holding the block, typing in the command "/mt hand". The mod will copy the block ID and metadata for you, so just paste the results into the config file, and remove the < and > brackets. Similarly, Forestry:resources is also a reference to the block ID and metadata of forestry's apatite ore block.

For Industrialcraft, you would use the process described above, except for giving yourself IC2 copper ore instead of Tinkers Constuct, and you should find that the block ID for IC2 copper ore is IC2:blockOreCopper.

For reference, here is what I put into the IC2.cfg that I created inside the Strata config folder:
# Configuration file

ores {

```
"IC2:blockOreCopper" {
    S:oreTexture=IC2:blockOreCopper
    S:stoneTexture=stone
}
```

}

stones {
}

I left out the other ores so you can learn to use the method I described above to figure them, and any ores/stones in other mods, out for yourself.

Please let me know if you have any further questions relating to this topic.

**Comment by lightning02** [comment]
First of all thanks for you kindness :)
Yes, I figured it out hardly testing about the name-ID thing, and I managed to make Mekanism and Industrialcraft working config file.
But actually I'm having some trouble adding ProjectRed Exploration and ReactorCraft ores :(
I've also tryed your method with minetweaker3 but seems that maybe I still have done some error?
This is the config I've tryed for project red for example;
![vecchia](https://cloud.githubusercontent.com/assets/11884147/15404739/31df8ea6-1dff-11e6-95cb-6d183a8c93f5.png)

![ok](https://cloud.githubusercontent.com/assets/11884147/15408046/881121d6-1e0e-11e6-8537-cbdd5555cfe7.png)

![1](https://cloud.githubusercontent.com/assets/11884147/15407157/da4d3246-1e09-11e6-83eb-65b2782fe6c9.png)

And this is what I get from /mt hand;
![abc](https://cloud.githubusercontent.com/assets/11884147/15404963/36953bca-1e00-11e6-9917-3b3e5591344f.png)

None of them worked for me :/

I've also tryed with reactorcraft but it even errored, (i'm gonna try more accurately on that btw)
![ghj](https://cloud.githubusercontent.com/assets/11884147/15404986/4cdf751c-1e00-11e6-9a3a-8d5712d449c3.png)

![ult](https://cloud.githubusercontent.com/assets/11884147/15405025/78039b56-1e00-11e6-9af7-0d4d48132e1a.png)

Edit: Tryied differently but still error.
![2](https://cloud.githubusercontent.com/assets/11884147/15407165/e647151c-1e09-11e6-9c65-f385f04e2108.png)

**Comment by blueyu2** [comment]
For Project Red: 
The .cfg file needs the modid, which can be found in the mcmod.info in ProjectRed-1.7.10-4.7.0pre12.95-World.jar
Alternatively, you could use the first half of /mt hand output (before the ':' )
Also, MineTweaker3 copies the block information for you, so you only need to paste the results into the config file (and remove the < and > brackets).

For reference, here is what I have for ProjRed|Exploration.cfg
# Configuration file

ores {

```
"ProjRed|Exploration:projectred.exploration.ore" {
    S:oreTexture=projectred:world/ruby_ore
    S:stoneTexture=stone
}
```

}

stones {
}

For ReactorCraft:
ReactorCraft, for whatever reason, doesn't have the modid in it's mcmod.info file, so you would need to use the alternative option I mentioned (using /mt hand output).

I think the issue is you have "ReactorCraft:Fluorite:2" instead of "ReactorCraft:reactorcraft_block_fluoriteore:2".

**Comment by lightning02** [comment]
on my first try it was like "ReactorCraft:Fluorite:2", but then I've tryed in fact  "ReactorCraft:reactorcraft_block_fluoriteore:2" and it keep getting error..  :/  I guess I should refer this to Reika tomorrow and see what he can say about it.
By the way thanks alot for projectred and the modinfo tip!
I had in fact to put the " | " symbol instead of " : " between "ProjRed" and "Exploration", that was my bad in the end, thanks for the patience :)

**Comment by blueyu2** [comment]
No problem, thanks for getting me to focus on a mod I lost interest in and abandoned :)

What version of ReactorCraft are you using? I was testing with V13b and have had no errors.

For reference, here is the ReactorCraft config file I made:
# Configuration file

ores {

```
"ReactorCraft:reactorcraft_block_ore:1" {
    S:oreTexture=reactorcraft:ore/pitchblende
    S:stoneTexture=stone
}

"ReactorCraft:reactorcraft_block_fluoriteore" {
    S:oreTexture=reactorcraft:ore/fluorite_blue
    S:stoneTexture=stone
}

"ReactorCraft:reactorcraft_block_fluoriteore:2" {
    S:oreTexture=reactorcraft:ore/fluorite_orange
    S:stoneTexture=stone
}

"ReactorCraft:reactorcraft_block_fluoriteore:5" {
    S:oreTexture=reactorcraft:ore/fluorite_red
    S:stoneTexture=stone
}
```

}

stones {
}

**Comment by lightning02** [comment]
abandoned? Oh gosh but your mod is GREAT! 
Really, I'm sayng this honestly, your mod is simple and absolutely great.
It try to make a procedural progress into minecraft, kinda like another game called Creativerse and this is nice. It force you to find and explore caves gradually, expecially combined with other mods and your mod also prevent you to just go down and find what you need at whatever height.
This still don't prevent people from making """houses""" inside some hole and be repaired from overworld mobs, but it's still a nice procedural addition.

Anyway, the I'm using latest version of reika mods like you do, DragonApi v13b, rotarycraft 13b, reactorcraft 13b, electricraft 13a. I've look more accurately in my cfg file since you said it worked for you, and in fact mine had an error in a string, I was missing a " .. yeah, just that one.. in fact now works.
I can't say the same for Electricraft btw :l

![02c38a8e106cc19e0b6f61831067942f49edf0ee2dcd9fa7ae pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15425229/50392848-1e87-11e6-9abc-70b6a7ece1d3.png)

**Comment by blueyu2** [comment]
Thanks for the kind words, but the idea behind this mod is from FlowerChild's mod [Better Than Wolves](http://sargunster.com/btw/index.php?title=Hardcore_Stratification). I just took the idea and rewrote it for 1.7.10. 

The problem with your ElecriCraft config file is that some of the ores listed have the wrong texture associated with them.

Here are the entries that need to be replaced/added:

```
"ElectriCraft:electricraft_block_ore" {
    S:oreTexture=electricraft:oreCopper
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:1" {
    S:oreTexture=electricraft:oreTin
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:2" {
    S:oreTexture=electricraft:oreSilver
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:3" {
    S:oreTexture=electricraft:oreNickel
    S:stoneTexture=stone
}
```

**Comment by lightning02** [comment]
Is this one correct? http://pastebin.com/xka1K42c
Because it still get errored

**Comment by blueyu2** [comment]
Looks like a " was missing at the end of ElectriCraft:electricraft_block_ore:1 and aluminum and platinum ore should end in 4 and 5 instead of 5 and 6.

Here is the ElectriCraft config file I made:

# Configuration file

ores {

```
"ElectriCraft:electricraft_block_ore" {
    S:oreTexture=electricraft:oreCopper
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:1" {
    S:oreTexture=electricraft:oreTin
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:2" {
    S:oreTexture=electricraft:oreSilver
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:3" {
    S:oreTexture=electricraft:oreNickel
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:4" {
    S:oreTexture=electricraft:oreAluminum
    S:stoneTexture=stone
}

"ElectriCraft:electricraft_block_ore:5" {
    S:oreTexture=electricraft:orePlatinum
    S:stoneTexture=stone
}
```

}

stones {
}

**Comment by lightning02** [comment]
Well, mhm, I guess I'll surrender for this mod.. at least I can disable the ores in the config and use Thermal Expansion ore + ore dictionary instead.
This is the last one that errore http://pastebin.com/X7uqTGUA but nevermind
By the way, there is a last thing I would alert you of, but maybe you already know about, well.. the chunk rendering issue that happens exploring undergroun., Probably related with optifine but it happen even with the chunk render is on "default"
![aaaaa](https://cloud.githubusercontent.com/assets/11884147/15438932/d1598f7a-1ece-11e6-8e33-33a4e0941c00.png)

**Comment by blueyu2** [comment]
The chunk rendering issue can be fixed by going into Options->Video Settings->Performance, and setting Lazy Chunk Loading to OFF.

The config file you posted is missing " at the end of ElectriCraft:electricraft_block_ore:1 and ElectriCraft:electricraft_block_ore:5. You can copy and paste the config file I posted earlier to fix it.

**Comment by lightning02** [comment]
Ohw.. this is embarrassing...
Is the second time I make a silly mistake and can't figure it out '-'
I don't know what to say, thanks for have such patience :/
By the way, do you mean turn on OFF the "Fast Render" in optifine performance section? Because it was already on off :o

**Comment by lightning02** [comment]
by the way, I'm gonna close this in favor of a more serious issue.
